# Generated by Django 3.1.1 on 2020-12-17 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201127_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('kindCd', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('kindNm', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sido',
            fields=[
                ('sidoCd', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('sidoNm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sigungu',
            fields=[
                ('sigunguCd', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('sigunguNm', models.CharField(max_length=20)),
                ('sidoCd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sido')),
            ],
        ),
    ]
