# Generated by Django 3.1.1 on 2020-12-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_kind_sido_sigungu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kind',
            new_name='KindCd',
        ),
    ]
